### PR TITLE
chore: resolve trivy alerts

### PR DESCRIPTION
**Pull request by shgokita**
## ✍ Description
Resolved following trivy alerts. Currently no alerts left.

- [x] trivy:AVD-AWS-0077 consider about backup_retention_period https://avd.aquasec.com/misconfig/avd-aws-0077
- [x] trivy:AVD-AWS-0133 consider about performance_insights https://avd.aquasec.com/misconfig/avd-aws-0133
- [x] trivy:AVD-AWS-0176 consider about IAM authentication https://avd.aquasec.com/misconfig/avd-aws-0176 related https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
- [x] trivy:AVD-AWS-0178 consider about vpc_flow_log https://avd.aquasec.com/misconfig/avd-aws-0178
- [x] trivy:AVD-AWS-0017 consider about kms https://avd.aquasec.com/misconfig/avd-aws-0017
- [x] trivy:AVD-AWS-0002 consider about Cache data encryption https://avd.aquasec.com/misconfig/avd-aws-0002
- [x] trivy:AVD-AWS-0104 consider about Security group rule allows egress to multiple public internet addresses https://avd.aquasec.com/misconfig/avd-aws-0104

S3 endpoints have also been deleted.
Deployed to AWS and confirmed to work.
In addition, the class of the DB instance has been changed from db.t3.micro to db.t3.midium in order to enable performance insights for the DB ( refer: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.Engines.html ).

## 📸 Test Result
```
► trivy config . --include-non-failures
infrastructure/example-dev (terraform)
======================================
Tests: 66 (SUCCESSES: 66, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

service/example-dev (terraform)
===============================
Tests: 46 (SUCCESSES: 46, FAILURES: 0, EXCEPTIONS: 0)
Failures: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

### CODE REVIEW

**Comment by shgokita** [comment]
[Task]: Trivy Caution Suggestion #143
https://github.com/FujitsuResearch/QuantumCloudPlatform/issues/143

**Comment by shgokita** [comment]
I revised db_performance_insights_enabled can be set as a variable.

**Comment by orangekame3** [comment]
@shgokita 
Thanks! Could you run `make docs` at root directory?

**Review by orangekame3 — APPROVED** [review]
Thanks!!🐱

**Pull request merged**
